// Yalnız demo modu (NEXT_PUBLIC_DEMO_MODE=true) için örnek hesaplar.
import { Profile } from '@/types/database';

export const INITIAL_PROFILES: Profile[] = [
  {
    id: 'user-hoca-1',
    email: 'hoca@ankara.edu.tr',
    full_name: 'Prof. Dr. Ali Kemal Arslan',
    role: 'hoca',
    kadro: 'hoca',
    yetki: 'admin',
    is_active: true,
    academic_title: 'Grup Lideri & Profesör',
    department: 'Fizik Anabilim Dalı',
    avatar_url: null,
    research_topics: ['Yoğun Madde Fiziği', 'DFT Hesaplamaları', '2D Malzemeler', 'Topolojik Yalıtkanlar'],
    scholar_url: 'https://scholar.google.com',
    orcid: '0000-0002-1825-0097',
    is_approved: true,
    created_at: '2026-01-10T10:00:00Z',
  },
  {
    id: 'user-admin-1',
    email: 'can.ozdemir@ankara.edu.tr',
    full_name: 'Can Özdemir',
    role: 'yonetici',
    kadro: 'doktora',
    yetki: 'admin',
    is_active: true,
    academic_title: 'Doktora Araştırmacısı (Grup Yöneticisi)',
    department: 'Fizik Mühendisliği Anabilim Dalı',
    avatar_url: null,
    research_topics: ['VASP', 'Fonon Hesaplamaları', 'Grafen Türevleri', 'TRUBA Cluster Yönetimi'],
    scholar_url: 'https://scholar.google.com',
    orcid: '0000-0003-4512-8821',
    is_approved: true,
    created_at: '2026-02-01T11:00:00Z',
  },
  {
    id: 'user-admin-2',
    email: 'zeynep.kaya@ankara.edu.tr',
    full_name: 'Zeynep Kaya',
    role: 'yonetici',
    kadro: 'doktora',
    yetki: 'admin',
    is_active: true,
    academic_title: 'Doktora Araştırmacısı (Grup Yöneticisi)',
    department: 'Fizik Anabilim Dalı',
    avatar_url: null,
    research_topics: ['Moleküler Dinamik (LAMMPS)', 'Termoelektrik Malzemeler', 'Python ile Veri Analizi'],
    scholar_url: 'https://scholar.google.com',
    orcid: '0000-0001-9921-3342',
    is_approved: true,
    created_at: '2026-02-15T09:30:00Z',
  },
  {
    id: 'user-student-1',
    email: 'burak.yilmaz@ankara.edu.tr',
    full_name: 'Burak Yılmaz',
    role: 'arastirmaci',
    kadro: 'yuksek_lisans',
    yetki: 'uye',
    is_active: true,
    academic_title: 'Yüksek Lisans Öğrencisi',
    department: 'Fizik Anabilim Dalı',
    avatar_url: null,
    research_topics: ['Manyetik İki Boyutlu Malzemeler', 'Spin Polarizasyonlu DFT'],
    scholar_url: 'https://scholar.google.com',
    orcid: '0009-0004-7128-4491',
    is_approved: true,
    created_at: '2026-03-01T14:00:00Z',
  },
  {
    id: 'user-student-2',
    email: 'elif.demir@ankara.edu.tr',
    full_name: 'Elif Demir',
    role: 'arastirmaci',
    kadro: 'doktora',
    yetki: 'uye',
    is_active: true,
    academic_title: 'Doktora Öğrencisi',
    department: 'Fizik Mühendisliği Anabilim Dalı',
    avatar_url: null,
    research_topics: ['Perovskit Güneş Hücreleri', 'Optik Özellikler', 'HSE06 Hibrit Fonksiyoneller'],
    scholar_url: 'https://scholar.google.com',
    orcid: '0009-0002-3391-1120',
    is_approved: true,
    created_at: '2026-03-10T10:00:00Z',
  },
];
